"""empty message

Revision ID: 48ec9c502eb3
Revises: a841559516bd
Create Date: 2016-05-28 17:37:48.227898

"""

# revision identifiers, used by Alembic.
revision = '48ec9c502eb3'
down_revision = 'a841559516bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
