"""empty message

Revision ID: a841559516bd
Revises: e618a4c75537
Create Date: 2016-05-28 17:32:09.483018

"""

# revision identifiers, used by Alembic.
revision = 'a841559516bd'
down_revision = 'e618a4c75537'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
